
export const ActionTypes = {
    PLUS_QUANTITY: "PLUS_QUANTITY",
    MINUS_QUANTITY: "MINUS_QUANTITY",
    GET_ALL_PRODUCT: "GET_ALL_PRODUCT",
    GET_NUMBER_CART: "GET_NUMBER_CART",
    ADD_CART: "ADD_CART",
    UPDATE_CART: "UPDATE_CART",
    DELETE_CART: "DELETE_CART",
    LOGGED_IN_CHECK: "LOGGED_IN_CHECK",
    LOGGED_OUT_CHECK: "LOGGED_OUT_CHECK",
    LOG_OUT_RESET: "LOG_OUT_RESET"
};

